// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     order_message.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type OrderMessagePayload struct {
	Order_id string `json:"order_id"`
}

const OrderMessagePayloadAvroCRC64Fingerprint = "*\x95(\xe7\xa2l^\x1e"

func NewOrderMessagePayload() OrderMessagePayload {
	r := OrderMessagePayload{}
	return r
}

func DeserializeOrderMessagePayload(r io.Reader) (OrderMessagePayload, error) {
	t := NewOrderMessagePayload()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeOrderMessagePayloadFromSchema(r io.Reader, schema string) (OrderMessagePayload, error) {
	t := NewOrderMessagePayload()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeOrderMessagePayload(r OrderMessagePayload, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Order_id, w)
	if err != nil {
		return err
	}
	return err
}

func (r OrderMessagePayload) Serialize(w io.Writer) error {
	return writeOrderMessagePayload(r, w)
}

func (r OrderMessagePayload) Schema() string {
	return "{\"fields\":[{\"logicalType\":\"UUID\",\"name\":\"order_id\",\"type\":\"string\"}],\"name\":\"OrderMessagePayload\",\"type\":\"record\"}"
}

func (r OrderMessagePayload) SchemaName() string {
	return "OrderMessagePayload"
}

func (_ OrderMessagePayload) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ OrderMessagePayload) SetInt(v int32)       { panic("Unsupported operation") }
func (_ OrderMessagePayload) SetLong(v int64)      { panic("Unsupported operation") }
func (_ OrderMessagePayload) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ OrderMessagePayload) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ OrderMessagePayload) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ OrderMessagePayload) SetString(v string)   { panic("Unsupported operation") }
func (_ OrderMessagePayload) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *OrderMessagePayload) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Order_id}

		return w

	}
	panic("Unknown field index")
}

func (r *OrderMessagePayload) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *OrderMessagePayload) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ OrderMessagePayload) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ OrderMessagePayload) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ OrderMessagePayload) HintSize(int)                     { panic("Unsupported operation") }
func (_ OrderMessagePayload) Finalize()                        {}

func (_ OrderMessagePayload) AvroCRC64Fingerprint() []byte {
	return []byte(OrderMessagePayloadAvroCRC64Fingerprint)
}

func (r OrderMessagePayload) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["order_id"], err = json.Marshal(r.Order_id)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *OrderMessagePayload) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["order_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Order_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for order_id")
	}
	return nil
}
